name: Docker Push

on:
  workflow_run:
    workflows: ["CI - Build & Test"]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Validate Secrets
        run: |
          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "DOCKER_USERNAME missing"
            exit 1
          fi

          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
            echo "DOCKER_PASSWORD missing"
            exit 1
          fi

          echo "Secrets OK"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Docker Login (safe)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: |
          docker build -t harmoniaseguros/hs_images_repository:latest .

      - name: Push Image
        run: |
          docker push harmoniaseguros/hs_images_repository:latest
